import { AaronDbEdgeSessionRepository } from "../session-state";
import { DemiurgeEngine, HandSynthesisRequest, SovereignEthicsEngine } from "../demiurge-engine";
import { resolveProviderApiKey } from "../provider-key-store";
import { pushFilesToGithub, createPullRequest } from "../github-coordinator";
import { IMPROVEMENT_PROPOSAL_SESSION_ID } from "../reflection-engine";
import type { SophiaHandProposal } from "../sophia-engine";
import { canRunEvolution } from "../economos-engine";

/**
 * demiurge-meta-hand
 * Monitors the Knowledge Nexus and Improvement Proposals for promoted Hands.
 * Synthesizes the implementation and submits a self-modifying PR to the factory repository.
 * 🧙🏾‍♂️ Meta-circularity in action.
 */
export async function runDemiurgeMetaHand(env: any, timestamp: string) {
  const db = env.AARONDB;
  const repo = new AaronDbEdgeSessionRepository(db, "session-runtime");
  const proposalRepo = new AaronDbEdgeSessionRepository(db, IMPROVEMENT_PROPOSAL_SESSION_ID);
  
  console.log("🧙🏾‍♂️ Demiurge Meta-Hand: Checking for Synthesis Proposals...");
 
  // 0. Phase 23 Gating: Check with Economos
  const allowed = await canRunEvolution(env);
  if (!allowed) {
    return { 
      status: "halted", 
      message: "Evolution loop halted by Economos due to low efficiency score.",
      prSubmitted: false,
      summary: "Halted: Low efficiency score."
    };
  }

  // 1. Fetch current proposals
  const proposalSession = await proposalRepo.getSession();
  if (!proposalSession) {
    return { status: "no-proposals", message: "No improvement proposals found.", prSubmitted: false, summary: "No proposals found." };
  }

  // 2. Identify "Promoted" Hand Proposals that haven't been implemented yet
  const handProposals = proposalSession.toolEvents
    .filter(e => e.toolName === "session-reflection" || e.toolName === "improvement-proposal-review")
    .flatMap(e => (e.metadata?.proposals || []) as any[])
    .filter(p => p.status === "promoted" && p.handId?.startsWith("hand:synthesized:"));

  if (handProposals.length === 0) {
    return { status: "idle", message: "No promoted hand synthesis proposals found.", prSubmitted: false, summary: "No promoted hand synthesis proposals." };
  }

  // 3. Process the first eligible proposal (simplicity: one meta-change at a time)
  const proposal = handProposals[0];
  const handId = proposal.handId.replace("hand:synthesized:", "synthetic-");
  
  console.log(`✨ Demiurge Meta-Hand: Synthesizing Hand [${handId}] based on proposal [${proposal.handId}]`);

  const demiurge = new DemiurgeEngine(env);
  const synthesisRequest: HandSynthesisRequest = {
    id: handId,
    label: proposal.name || `Synthetic Hand ${handId}`,
    description: proposal.description || "Autonomously generated capability.",
    logicIntent: proposal.proposedImplementation || proposal.intentPattern || "No implementation provided.",
    scheduleCrons: ["0 * * * *"] // Default: hourly
  };
  
  // Phase 23 Ethics Gating
  if (!SovereignEthicsEngine.validateIntent(synthesisRequest.logicIntent)) {
    return {
      status: "rejected", 
      message: "Proposed hand intent violates Sovereign Ethics principles.",
      prSubmitted: false,
      summary: "Ethics Violation: Intent rejected."
    };
  }

  const sourceCode = await demiurge.synthesizeHand(synthesisRequest);

  // 4. Submit Self-Modifying PR
  const githubToken = await resolveProviderApiKey({ env, database: db, provider: "github" });
  if (!githubToken) {
    console.error("❌ GitHub Token not found. Cannot submit meta-PR.");
    return { status: "error", message: "GitHub token missing.", prSubmitted: false, summary: "Error: GitHub token missing." };
  }

  const branchName = `meta/evolution-${handId}-${Date.now().toString().slice(-4)}`;
  const fileName = `src/hands/${handId}-hand.ts`;

  try {
    // Note: In a real Cloudflare Worker, we can't easily check out the repo and commit.
    // We use the GitHub API to create a branch and push the new file.
    
    // For this simulation/implementation, we assume owner/repo are in env or inferred.
    const owner = env.GITHUB_OWNER || "brixelectronics";
    const repoName = env.GITHUB_REPO || "aaronclaw";

    console.log(`📦 Demiurge Meta-Hand: Creating branch ${branchName} and pushing ${fileName}...`);
    
    // We'll use a simplified flow: Push to new branch, then create PR
    await pushFilesToGithub(githubToken, owner, repoName, branchName, [{
      path: fileName,
      content: sourceCode
    }], `Meta-circular Evolution: Synthesizing ${handId} Hand 🧙🏾‍♂️`);

    await createPullRequest(githubToken, owner, repoName, {
      title: `Transcendent Evolution: Synthesize ${handId} Hand`,
      body: `This PR was autonomously generated by the **Demiurge Meta-Hand**.\n\n### Rationale\n${proposal.description}\n\n### Intent\n${proposal.intentPattern}\n\n🧘🏾‍♂️ Simplicity through self-evolution.`,
      head: branchName,
      base: "main"
    });

    // 5. Assert the evolution signal
    await repo.assertSignal({
      kind: "META_EVOLUTION_PR_SUBMITTED",
      payload: { handId, branchName, fileName, proposalId: proposal.handId },
      target: "operator"
    });

    return { 
      status: "success", 
      message: `Meta-circular PR submitted for ${handId}.`,
      prSubmitted: true,
      summary: `Synthesized ${handId} and submitted PR.`,
      branch: branchName 
    };

  } catch (error: any) {
    console.error("❌ Meta-evolution failed:", error);
    return { status: "error", message: error.message, prSubmitted: false, summary: `Error: ${error.message}` };
  }
}
