import { AaronDbEdgeSessionRepository } from "./session-state";

export interface HandSynthesisRequest {
  id: string;
  label: string;
  description: string;
  logicIntent: string;
  scheduleCrons: string[];
}

export interface AccessPolicyDSL {
  version: string;
  defaultAction: "allow" | "deny";
  rules: {
    pathPattern: string;
    allowRoles?: string[];
    denyRoles?: string[];
    allowUnauthenticated?: boolean;
  }[];
}

/**
 * Evaluates whether a request should be allowed based on policy and current context.
 */
export function evaluateDemiurgeAccess(policy: AccessPolicyDSL, path: string, role?: string): boolean {
  for (const rule of policy.rules) {
    const pattern = rule.pathPattern.replace(/\*/g, ".*");
    const regex = new RegExp(`^${pattern}$`);

    if (regex.test(path)) {
      // 1. Check denyRoles first
      if (role && rule.denyRoles?.includes(role)) {
        return false;
      }

      // 2. Check allowUnauthenticated
      if (!role && rule.allowUnauthenticated) {
        return true;
      }

      // 3. Check allowRoles
      if (role && rule.allowRoles) {
        if (rule.allowRoles.includes(role)) {
            return true;
        } else {
            // Rule matches path but role is not allowed. 
            // In a strict ordering system, this is usually a deny.
            return false;
        }
      }

      // If no roles specified but path matched and it's not unauthenticated, it hits the next rule or default.
    }
  }

  return policy.defaultAction === "allow";
}

export class DemiurgeEngine {
  constructor(private env: any) {}

  /**
   * Synthesizes a new Hand implementation based on architectural intent.
   * Follows Rich Hickey's principles: Simple, decoupled, and data-driven.
   */
  async synthesizeHand(request: HandSynthesisRequest): Promise<string> {
    console.log(`🧙🏾‍♂️ Demiurge: Synthesizing Hand [${request.id}]...`);
    
    // 1. Validate via Sovereign Ethics Engine
    const ethicalAudit = await this.auditSynthesis(request);
    if (!ethicalAudit.valid) {
      throw new Error(`❌ Sovereign Ethics Violation: ${ethicalAudit.reason}`);
    }

    // 2. Generate TypeScript source code
    const sourceCode = this.generateHandSource(request);

    return sourceCode;
  }

  private async auditSynthesis(request: HandSynthesisRequest): Promise<{ valid: boolean; reason?: string }> {
    // Sovereign Ethics Engine rules:
    // 1. No direct RPC calls between hands.
    // 2. All state must flow through AaronDB facts.
    // 3. Complexity must be bounded.
    
    if (request.logicIntent.includes("callHand") || request.logicIntent.includes("fetch(")) {
      return { valid: false, reason: "Direct coupling or unmanaged external calls detected. Use AaronDB signals." };
    }

    return { valid: true };
  }

  private generateHandSource(request: HandSynthesisRequest): string {
    const template = `
import { AaronDbEdgeSessionRepository } from "../session-state";
import { MeshSignal } from "../session-state";

/**
 * ${request.label}
 * ${request.description}
 * Autonomously generated by Demiurge Meta-Engine. 🧙🏾‍♂️
 */
export async function run${this.pascalCase(request.id)}(env: any, timestamp: string) {
  const repo = new AaronDbEdgeSessionRepository(env.AARONDB, "session-runtime");
  
  console.log("🚀 Running autonomous Hand: ${request.label}");

  // Logic Intent Implementation:
  // ${request.logicIntent}
  
  // Default: Assert self-completion signal
  await repo.assertSignal({
    kind: "HAND_EXECUTION_COMPLETE",
    payload: { handId: "${request.id}", timestamp },
    target: "mesh-coordinator"
  });

  return { status: "success", handId: "${request.id}" };
}
`;
    return template.trim();
  }

  private pascalCase(str: string): string {
    return str.split("-").map(part => part.charAt(0).toUpperCase() + part.slice(1)).join("");
  }
}

/**
 * Sovereign Ethics Engine: Ensures self-evolution adheres to Schematic purity.
 */
export const SovereignEthicsEngine = {
  validateIntent(intent: string): boolean {
    const forbidden = ["mutable", "globalState", "blocking"];
    return !forbidden.some(word => intent.includes(word));
  }
};
