import type { JsonObject } from "./session-state";

export interface GithubRepoConfig {
  owner: string;
  repo: string;
  description?: string;
  private?: boolean;
}

export interface GithubFileChange {
  path: string;
  content: string;
}

export interface GithubWorkflowStatus {
  id: number;
  status: "queued" | "in_progress" | "completed";
  conclusion: "success" | "failure" | "neutral" | "cancelled" | "timed_out" | "action_required" | "skipped" | null;
  html_url: string;
  run_number: number;
  created_at: string;
}

export async function runGithubCoordinator(env: Pick<Env, "GEMINI_API_KEY" | "AARONDB">): Promise<JsonObject> {
  // This is the entry point from hands-runtime.ts
  // For Phase 2, we will keep it simple and just return a status for now
  // while we build out the helper functions below.
  return {
    action: "coordinated",
    timestamp: new Date().toISOString(),
    status: "ready-for-commands",
    capabilities: ["create-repository", "push-files", "create-pull-request"]
  };
}

export async function createGithubRepository(
  token: string,
  config: GithubRepoConfig
): Promise<JsonObject> {
  const response = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: {
      Authorization: `token ${token}`,
      "Accept": "application/vnd.github.v3+json",
      "User-Agent": "AaronClaw-Software-Factory",
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      name: config.repo,
      description: config.description ?? "Generated by AaronClaw Software Factory",
      private: config.private ?? true,
      auto_init: true
    })
  });

  if (!response.ok) {
    const error = await response.json() as any;
    throw new Error(`GitHub Repository Creation Failed: ${error.message || response.statusText}`);
  }

  return await response.json() as JsonObject;
}

export async function pushFilesToGithub(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  changes: GithubFileChange[],
  message: string
): Promise<JsonObject> {
  // 🧙🏾‍♂️ Rich Hickey: Push files incrementally or as a single commit.
  // We'll use the "Create or update file contents" API for each file for simplicity in Phase 2.
  // In a more complex setup, we'd use the Git Trees API.

  const results: JsonObject[] = [];

  for (const change of changes) {
    // First, try to get the file SHA if it exists (for updates)
    const getFileResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${change.path}?ref=${branch}`, {
      headers: {
        Authorization: `token ${token}`,
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AaronClaw-Software-Factory"
      }
    });

    let sha: string | undefined;
    if (getFileResponse.ok) {
      const fileData = await getFileResponse.json() as any;
      sha = fileData.sha;
    }

    const putResponse = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${change.path}`, {
      method: "PUT",
      headers: {
        Authorization: `token ${token}`,
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "AaronClaw-Software-Factory",
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        message: `${message}: ${change.path}`,
        content: btoa(change.content),
        branch,
        sha
      })
    });

    if (!putResponse.ok) {
      const error = await putResponse.json() as any;
      throw new Error(`GitHub File Push Failed [${change.path}]: ${error.message || putResponse.statusText}`);
    }

    results.push(await putResponse.json() as JsonObject);
  }

  return { status: "succeeded", filesUpdated: results.length };
}

export async function createPullRequest(
  token: string,
  owner: string,
  repo: string,
  input: {
    title: string;
    body: string;
    head: string;
    base: string;
  }
): Promise<JsonObject> {
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: "POST",
    headers: {
      Authorization: `token ${token}`,
      "Accept": "application/vnd.github.v3+json",
      "User-Agent": "AaronClaw-Software-Factory",
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      title: input.title,
      body: input.body,
      head: input.head,
      base: input.base
    })
  });

  if (!response.ok) {
    const error = await response.json() as any;
    throw new Error(`GitHub Pull Request Creation Failed: ${error.message || response.statusText}`);
  }

  return await response.json() as JsonObject;
}
export async function setupGithubActions(
  token: string,
  owner: string,
  repo: string
): Promise<JsonObject> {
  // 🧙🏾‍♂️ Phase 2: Generating CI/CD trajectories.
  // We'll push a standard Wrangler deployment workflow.
  const workflowContent = `name: Deploy Agent
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: \${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: \${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
`;

  return await pushFilesToGithub(
    token,
    owner,
    repo,
    "main",
    [{
      path: ".github/workflows/deploy.yml",
      content: workflowContent
    }],
    "Setup CI/CD via AaronClaw Software Factory"
  );
}

export async function getLatestWorkflowRun(
  token: string,
  owner: string,
  repo: string
): Promise<GithubWorkflowStatus | null> {
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/actions/runs?per_page=1`, {
    headers: {
      Authorization: `token ${token}`,
      "Accept": "application/vnd.github.v3+json",
      "User-Agent": "AaronClaw-Software-Factory"
    }
  });

  if (!response.ok) {
    console.error(`GitHub Workflow Run Fetch Failed: ${response.statusText}`);
    return null;
  }

  const data = await response.json() as { workflow_runs: GithubWorkflowStatus[] };
  return data.workflow_runs[0] || null;
}

export async function getGithubFile(
  token: string,
  owner: string,
  repo: string,
  path: string,
  branch = "main"
): Promise<{ content: string; sha: string } | null> {
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${branch}`, {
    headers: {
      Authorization: `token ${token}`,
      "Accept": "application/vnd.github.v3+json",
      "User-Agent": "AaronClaw-Software-Factory"
    }
  });

  if (!response.ok) return null;

  const data = await response.json() as any;
  return {
    content: atob(data.content),
    sha: data.sha
  };
}

export async function setupGithubSecret(
  token: string,
  owner: string,
  repo: string,
  name: string,
  value: string
): Promise<void> {
  console.log(`[GitHub Secret] Provisioning ${name} to ${owner}/${repo} (requires sodium encryption)`);
}
